version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:latest
    working_directory: ~/emotion-emoji

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
	  # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/emotion-emoji
          paths: .

deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/emotion-emoji
      - run:
          name: samelogic
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish